# docker-compose example for tenderduty, copy this file to docker-compose.yml and edit to suit.
#
# Start from the files in examples/. For firewall and HTTPS setup see docs/install.md.
version: '3.2'

volumes:
  home:

services:
  tenderduty:
    build: .
    command: ""
    ports:
      - "8888:8888"   # Dashboard
      - "28686:28686" # Prometheus exporter
    volumes:
      - home:/var/lib/tenderduty
      - ./config.yml:/var/lib/tenderduty/config.yml
      - ./chains.d:/var/lib/tenderduty/chains.d/
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    restart: unless-stopped
